# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qWg47rPdzSLj1ys0V7XXfXUQHK3utvTm
"""

pip install augmentTS

from augmentts.augmenters.vae import LSTMVAE, VAEAugmenter

# create a variational autoencoder
vae = LSTMVAE(series_len=100)
# create an augmenter
augmenter = VAEAugmenter(vae)

import pandas as pd

# Load the CSV file
data = pd.read_csv("/content/sales_train_evaluation.csv")

# Print the first few rows of the DataFrame
print(data.head())

from augmentts.augmenters.vae import LSTMVAE, VAEAugmenter

# create a variational autoencoder
vae = LSTMVAE(series_len=100)
# create an augmenter
augmenter = VAEAugmenter(vae)

import tensorflow as tf

sequence_length = 100
num_features = 1947
latent_dim = 100

vae = LSTMVAE(latent_dim=latent_dim)

# Create an augmenter
augmenter = VAEAugmenter(vae)

augmenter.sample(n=1000)

augmenter.sample(n=1000, sigma=0.2)